services:
  postgres_auth:
    image: postgres:latest
    container_name: PostgresAuth
    restart: unless-stopped
    environment:
      POSTGRES_USER: sysAdmin
      POSTGRES_PASSWORD: sam
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - ./packages/sql/auth.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata_auth:/var/lib/postgresql/data
    shm_size: 256mb

  postgres_matching:
    image: postgres:latest
    container_name: PostgresMatching
    restart: unless-stopped
    environment:
      POSTGRES_USER: sysAdmin
      POSTGRES_PASSWORD: sam
      POSTGRES_DB: matching
    ports:
      - "5433:5432"
    volumes:
      - ./packages/sql/matching.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata_matching:/var/lib/postgresql/data
    shm_size: 256mb

  redis:
    image: redis:latest
    container_name: Redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: > 
      redis-server
      -- maxmemory 100mb
      -- maxmemory-policy allkeys-lru

  rabbitmq: 
    image: rabbitmq:management
    container_name: RabbitMQ
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
     - rabbitmq:/var/lib/rabbitmq
  
  mongo:
    image: mongo:latest
    container_name: MongoDB
    restart: unless-stopped
    environment: 
      MONGO_INITDB_ROOT_USERNAME: sysAdmin
      MONGO_INITDB_ROOT_PASSWORD: sam
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata_auth:
  pgdata_matching:
  mongodata:
  rabbitmq:
